### ISSUE TITLE
证书推送到CDN，能不能每次名字都一样，不然CDN那边还得重新选。

### ISSUE THREAD

**Issue by dxhuii** [0xJacky/cdn_cert#1]
现在推送到证书列表中，名字都不一样，还得去CDN配置那边选一下。好像还是有点麻烦，能不能名字一样，覆盖之前的证书呢？还有，现在生成的证书，可能是多个域名用一个证书，能不能实现，一组域名对应一个证书呢？现在是一个域名，不管是二级还是一级，都是单独对应一个证书，这样的话，就要单独生成很多证书。

**Comment by 0xJacky** [comment]
提交到阿里云 CDN 的证书名称是不能相同的
所以我采用「域名+提交时间」的格式来命名证书

提交成功之后是不需要到控制台选择的

**Comment by dxhuii** [comment]
嗯，测试了，确实不需要审核。有空的时候，我一个一个弄一下。
