### ISSUE TITLE
跑不起来呢

### ISSUE THREAD

**Issue by ghostry** [0xJacky/cdn_cert#4]
docker logs cdn_cert
python3: can't open file '/app/cron.py': [Errno 2] No such file or directory

**Comment by 0xJacky** [comment]
有正确地映射项目文件到容器中吗

**Comment by ghostry** [comment]
> 有正确地映射项目文件到容器中吗

我搞错了，app映射成了我的项目，原来要映射这个项目。

现在提示Result: Forbidden.RAM

是要开什么权限呢？已经开了云盾证书管理

**Comment by 0xJacky** [comment]
CDN 的权限也开一下

**Comment by ghostry** [comment]
> CDN 的权限也开一下

谢谢，可以了，这个好像会导致云盾证书那里，上传证书越来越多？

**Comment by 0xJacky** [comment]
正确的，因为阿里云不允许上传同名证书
